POST http://localhost:8001/member/passenger/save
Content-Type: application/json
token: {{token}}

{
  "memberId": "1",
  "name": "stx",
  "idCard": "123456789",
  "type": "1"
}

###
POST http://localhost:8001/member/passenger/save
Content-Type: application/json
token: {{token}}

{
  "name": "张三",
  "idCard": "1234567839",
  "type": "1"
}

###
GET http://localhost:8001/member/passenger/query-list?page=1&size=2
Content-Type: application/json
token: {{token}}

###
POST http://localhost:8001/member/passenger/save
Content-Type: application/json
token: {{token}}

{
  "name": "张三",
  "idCard": "1234567839",
  "type": "2"
}

###
POST http://localhost:8001/member/passenger/save
Content-Type: application/json
token: {{token}}

{
  "id": 1726888092096401405,
  "memberId": 1,
  "name": "张三",
  "idCard": "1234567839",
  "type": "1"
}

###
DELETE http://localhost:8001/member/passenger/delete/1726852402038050816
Content-Type: application/json
token: {{token}}
