POST http://localhost:8001/member/passenger/save
Content-Type: application/json
token: {{token}}

{
  "memberId": "1",
  "name": "stx",
  "idCard": "123456789",
  "type": "1"
}

###
POST http://localhost:8001/member/passenger/save
Content-Type: application/json
token: {{token}}

{
  "name": "stx",
  "idCard": "123456789",
  "type": "1"
}

###
GET http://localhost:8001/member/passenger/query-list
Content-Type: application/json
token: {{token}}
