server:
  port: 8002
  servlet:
    context-path: /business

spring:
  application:
    name: business
  datasource:
    url: jdbc:mysql://localhost:3306/train_business?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    top.stx.train.business.mapper: trace
