server:
  port: 8002
  servlet:
    context-path: /business

spring:
  application:
    name: business
  datasource:
    url: jdbc:mysql://localhost:3306/train_business?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
#  cloud:
#    sentinel:
#      transport:
#        port: 8719
#        dashboard: localhost:8080

rocketmq:
  name-server: http://1.94.53.29:9876
  producer:
    group: default

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    local-cache-scope: statement
logging:
  level:
    top.stx.train.business.mapper: trace
